# Basic Usage Example
# This example shows the minimal configuration required to use the UMS Identity module

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-west-2"
}

# Use the UMS Identity module from Azure DevOps
module "ums_identity" {
  source = "git::https://ums-projects@dev.azure.com/ums-projects/Unified%20microservices/_git/ums-identity-dynamodb//terraform"

  # Basic configuration
  environment = "dev"

  # Optional: Override default table names
  users_table_name            = "my-app-users"
  tokens_table_name           = "my-app-tokens"
  temporary_tokens_table_name = "my-app-temp-tokens"
  user_roles_table_name       = "my-app-user-roles"

  # Use default PAY_PER_REQUEST billing (recommended for development)
  billing_mode = "PAY_PER_REQUEST"

  # Tags
  common_tags = {
    Environment = "dev"
    Project     = "MyApp"
    Component   = "Identity"
    Owner       = "Development Team"
  }
}

# Output important values
output "table_names" {
  description = "All DynamoDB table names"
  value       = module.ums_identity.all_table_names
}

output "configuration_for_dotnet" {
  description = "Configuration object for .NET application"
  value       = module.ums_identity.identity_configuration
}

# Create an example appsettings.json file
resource "local_file" "appsettings" {
  content = jsonencode({
    Identity = merge(module.ums_identity.identity_configuration, {
      Jwt = {
        Secret                     = "your-secret-key-here-must-be-at-least-32-characters"
        Issuer                     = "your-app"
        Audience                   = "your-app-users"
        AccessTokenLifetimeMinutes = 15
      }
      SendWelcomeEmail = true
    })
  })
  filename = "${path.module}/appsettings.generated.json"
}

# Example IAM role for EC2 instances running the application
resource "aws_iam_role" "app_role" {
  name = "ums-identity-app-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
      }
    ]
  })

  tags = {
    Environment = "dev"
    Project     = "MyApp"
    Component   = "Identity"
  }
}

# Attach the DynamoDB policy generated by the module
resource "aws_iam_role_policy" "app_dynamodb_access" {
  name   = "dynamodb-access"
  role   = aws_iam_role.app_role.id
  policy = module.ums_identity.identity_dynamodb_policy
}

# Create instance profile for EC2
resource "aws_iam_instance_profile" "app_profile" {
  name = "ums-identity-app-profile"
  role = aws_iam_role.app_role.name
}
